### ISSUE TITLE
Weird issue when trying to add zimgui to project.

### ISSUE THREAD

**Issue by Falkgaard** [zig-gamedev/zgui#66]
I'm using Zig 0.15.1 on WIndows, trying to make an app with GLFW+GL3 as the backend while learning Zig. My build file looks like this pretty much:

```
const std = @import("std");

pub fn build( b: *std.Build ) void {
    const target = b.standardTargetOptions(  .{} );
    const optimize = b.standardOptimizeOption( .{} );

    // Create app module:
    const app_module = b.createModule(.{
        .root_source_file = b.path("src/demo.zig"),
        .target = target,
        .optimize = optimize,
    });
    // Add compile-time info constants (for app name and semantic version):
    const app_info_options = b.addOptions();
    // ...
    app_module.addOptions("app_info", app_info_options );

    // Create app binary:
    const app_exe = b.addExecutable(.{
        .name = "demo",
        .root_module = app_module,
    });

    const zglfw_dep = b.dependency( "zglfw", .{ .target = target } );
    app_exe.root_module.addImport( "zglfw", zglfw_dep.module("root") );
    app_exe.linkLibrary( zglfw_dep.artifact("glfw") );

    const zopengl_dep = b.dependency("zopengl", .{} );
    app_exe.root_module.addImport( "zopengl", zopengl_dep.module("root") );

    const zmath_dep = b.dependency( "zmath", .{} );
    app_exe.root_module.addImport( "zmath", zmath_dep.module("root") );

    const zstbi_dep = b.dependency( "zstbi", .{} );
    app_exe.root_module.addImport( "zstbi", zstbi_dep.module("root") );

    const zgui_dep = b.dependency("zgui", .{
        .backend = .glfw_opengl3,
        .shared = false,
    });
    app_exe.root_module.addImport( "zgui", zgui_dep.module("root") );
    app_exe.linkLibrary( zgui_dep.artifact("imgui") );

    b.installArtifact( app_exe );
}
```

And the deps in my `build.zig.zon` looks like: 

```
    .dependencies = .{
        .zglfw = .{
            .url = "git+https://github.com/zig-gamedev/zglfw#82da052ccace5690f323876046d3062c9c573283",
            .hash = "zglfw-0.10.0-dev-zgVDNK6oIQAamIbSG6JGubpBiQSxrv_lymMIsub2DBNa",
        },
        .zopengl = .{
            .url = "git+https://github.com/zig-gamedev/zopengl#e5b00b6957ceeacc7e980d6f34b1da663e39554c",
            .hash = "zopengl-0.6.0-dev-5-tnz9g8CQBbUiEouos-P6EE87Gf0GWUzsMh9XDvAtLP",
        },
        .zmath = .{
            .url = "git+https://github.com/zig-gamedev/zmath#3a5955b2b72cd081563fbb084eff05bffd1e3fbb",
            .hash = "zmath-0.11.0-dev-wjwivdMsAwD-xaLj76YHUq3t9JDH-X16xuMTmnDzqbu2",
        },
        .zstbi = .{
            .url = "git+https://github.com/zig-gamedev/zstbi#2c4b3100ccb7aed90ecc9439030899764e2a8d47",
            .hash = "zstbi-0.11.0-dev-L0Ea_yaWBwAHwFoCuyjkFyaiSsbjt4UOrkntR0c_nmzz",
        },
        .zgui = .{
            .url = "git+https://github.com/zig-gamedev/zgui#7bc9461997c402c1be9bc716388399404df1686e",
            .hash = "zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c",
        },
    },
```

Everything was compiling fine until I tried to add zgui, but now I get some build error mentioning freetype:

```
C:\Users\Laptop\AppData\Local\zig\p\freetype-0.0.0-AAAAAA5JcwBMujojfNLEq5g_WijZtU56mRLYx8bjjiMU\build.zig:10:18: error: no field or member function named 'addStaticLibrary' in 'Build'
    const lib = b.addStaticLibrary(.{
                ~^~~~~~~~~~~~~~~~~
C:\Users\Laptop\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.15.1\lib\std\Build.zig:1:1: note: struct declared here
const std = @import("std.zig");
^~~~~
C:\Users\Laptop\AppData\Local\zig\p\freetype-0.0.0-AAAAAA5JcwBMujojfNLEq5g_WijZtU56mRLYx8bjjiMU\build.zig:10:18: note: method invocation only supports up to one level of implicit pointer dereferencing
C:\Users\Laptop\AppData\Local\zig\p\freetype-0.0.0-AAAAAA5JcwBMujojfNLEq5g_WijZtU56mRLYx8bjjiMU\build.zig:10:18: note: use '.*' to dereference pointer
referenced by:
    runBuild__anon_126514: C:\Users\Laptop\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.15.1\lib\std\Build.zig:2214:33
    dependencyInner__anon_117658: C:\Users\Laptop\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.15.1\lib\std\Build.zig:2195:29
    13 reference(s) hidden; use '-freference-trace=15' to see all references
```

Any ideas what's wrong?

**Comment by tonitch** [comment]
I believe this is a similar bug I had on my system (Linux) when upgrading to 0.15.1

I believe it solved itself by deleting the cache. In your case the freetype file mentioned maybe 🤔

**Comment by Falkgaard** [comment]
> I believe this is a similar bug I had on my system (Linux) when upgrading to 0.15.1
> 
> I believe it solved itself by deleting the cache. In your case the freetype file mentioned maybe 🤔

Ah, thank you very much! Doing that and having `.with_freetype = false,` seems to have moved the build along a bit further (if I set it to true, build, and then false again and rebuild it ends up borked again until I manually delete the freetype it seems), but now the wrapped imgui seems to be missing OpenGL symbol visibility instead:

```
install
└─ install demo
   └─ compile exe demo Debug native
      └─ compile lib imgui Debug native 21 errors
:1:1: error: argument unused during compilation: '-fno-rtlib-defaultlib'
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:232:5: error: unknown type name 'GLuint'
    GLuint          GlVersion;               // Extracted at runtime using GL_MAJOR_VERSION, GL_MINOR_VERSION queries (e.g. 320 for GL 3.2)
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:237:5: error: unknown type name 'GLint'
    GLint           GlProfileMask;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:238:5: error: unknown type name 'GLint'
    GLint           MaxTextureSize;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:239:5: error: unknown type name 'GLuint'
    GLuint          ShaderHandle;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:240:5: error: unknown type name 'GLint'
    GLint           AttribLocationTex;       // Uniforms location
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:241:5: error: unknown type name 'GLint'
    GLint           AttribLocationProjMtx;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:242:5: error: unknown type name 'GLuint'
    GLuint          AttribLocationVtxPos;    // Vertex attributes location
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:243:5: error: unknown type name 'GLuint'
    GLuint          AttribLocationVtxUV;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:244:5: error: unknown type name 'GLuint'
    GLuint          AttribLocationVtxColor;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:246:5: error: unknown type name 'GLsizeiptr'
    GLsizeiptr      VertexBufferSize;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:247:5: error: unknown type name 'GLsizeiptr'
    GLsizeiptr      IndexBufferSize;
    ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:323:59: error: use of undeclared identifier 'GL_VERSION'
    const char* gl_version_str = (const char*)glGetString(GL_VERSION);
                                                          ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:331:5: error: unknown type name 'GLint'
    GLint major = 0;
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
                  ^
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
                  ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_gui_impl_opengl3.cpp:334:19: error: use of undeclared identifier 'GL_MINOR_VERSION'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
                  ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:337:22: error: use of undeclared identifier 'GLuint'
    glGetIntegerv(GL_MINOR_VERSION, &minor);
                  ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:337:22: error: use of undeclared identifier 'GLuint'
    bd->GlVersion = (GLuint)(major * 100 + minor * 10);
                     ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:338:19: error: use of undeclared identifier 'GL_MAX_TEXTURE_SIZE'
    glGetIntegerv(GL_MAX_TEXTURE_SIZE, &bd->MaxTextureSize);
                  ^
C:\Users\Laptop\AppData\Local\zig\p\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\libs/imgui/backends/imgui_impl_opengl3.cpp:398:5: error: unknown type name 'GLint'                                                       
    GLint current_texture;
    ^
:1:1: error: too many errors emitted, stopping now
error: the following command failed with 21 compilation errors:
"C:\\Users\\Laptop\\AppData\\Roaming\\Code\\User\\globalStorage\\ziglang.vscode-zig\\zig\\x86_64-windows-0.15.1\\zig.exe" build-lib -cflags -fno-sanitize=undefined -Wno-elaborated-enum-base -Wno-error=date-time  -- "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\src\\zgui.cpp" -cflags -fno-sanitize=undefined -Wno-elaborated-enum-base -Wno-error=date-time  -- "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/imgui.cpp" "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/imgui_widgets.cpp" "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/imgui_tables.cpp" "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/imgui_draw.cpp" "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/imgui_demo.cpp" -cflags -fno-sanitize=undefined -Wno-elaborated-enum-base -Wno-error=date-time  -DIMGUI_IMPL_OPENGL_LOADER_CUSTOM -- "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/backends/imgui_impl_glfw.cpp" "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs/imgui/backends/imgui_impl_opengl3.cpp" -ODebug -I "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs" -I "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zgui-0.6.0-dev--L6sZO_HbQBW30QfIGHgKhjxShc_o4wBeJZ0hga5IA0c\\libs\\imgui" -I "C:\\Users\\Laptop\\AppData\\Local\\zig\\p\\zglfw-0.10.0-dev-zgVDNLyhIQCZR_rbIf7hnCKuifzcmPOLOQhd_hrqq8cl\\libs/glfw/include" -DIMGUI_DISABLE_OBSOLETE_FUNCTIONS= -Mroot -lc++ -lc --cache-dir .zig-cache --global-cache-dir "C:\\Users\\Laptop\\AppData\\Local\\zig" --name imgui -static --zig-lib-dir "C:\\Users\\Laptop\\AppData\\Roaming\\Code\\User\\globalStorage\\ziglang.vscode-zig\\zig\\x86_64-windows-0.15.1\\lib\\" --listen=-

Build Summary: 10/14 steps succeeded; 1 failed
install transitive failure
├─ install libfalk success
│  └─ compile lib libfalk Debug native success 6s MaxRSS:84M
└─ install demo transitive failure
   └─ compile exe demo Debug native transitive failure
      ├─ WriteFile cached
      ├─ compile lib libfalk Debug native (reused)
      ├─ WriteFile  success
      ├─ compile lib glfw Debug native success 6s MaxRSS:53M
      ├─ WriteFile success
      ├─ compile lib imgui Debug native 21 errors
      ├─ compile lib libfalk Debug native (reused)
      ├─ compile lib glfw Debug native (reused)
      ├─ compile lib imgui Debug native (reused)
      ├─ options success
      ├─ options success
      ├─ options success
      └─ options success

error: the following build command failed with exit code 1:
.zig-cache\o\ea4e731bc9c50e37a016144b8edb337f\build.exe C:\Users\Laptop\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.15.1\zig.exe C:\Users\Laptop\AppData\Roaming\Code\User\globalStorage\ziglang.vscode-zig\zig\x86_64-windows-0.15.1\lib C:\V\Zig\prng .zig-cache C:\Users\Laptop\AppData\Local\zig --seed 0x90006724 -Z566d2c523118d171 -Denable-demo --summary all
```

**Comment by tonitch** [comment]
Okay so to explain your problem in case you didn't figure it out.
Basically, imgui's opengl backend doesn't include opengl because this could cause problem on some system. Instead, we use their custom loader with this line : https://github.com/zig-gamedev/zgui/blob/7bc9461997c402c1be9bc716388399404df1686e/build.zig#L280C1-L280C16
which [include](https://github.com/ocornut/imgui/blob/d4f722d5b289d4d75b775acfb0a4b41e7df472a7/backends/imgui_impl_opengl3.cpp#L180) all the [symbols](https://github.com/ocornut/imgui/blob/d4f722d5b289d4d75b775acfb0a4b41e7df472a7/backends/imgui_impl_opengl3_loader.h#L147) you are missing. So the problem is that this header is not included in some way.

I'm mainly focusing on the sdl part of this project so I don't have any project to test this on. maybe you have some sample project I could try? or maybe the info I gave could help you figure this out ?

**Comment by Falkgaard** [comment]
> Okay so to explain your problem in case you didn't figure it out. Basically, imgui's opengl backend doesn't include opengl because this could cause problem on some system. Instead, we use their custom loader with this line : https://github.com/zig-gamedev/zgui/blob/7bc9461997c402c1be9bc716388399404df1686e/build.zig#L280C1-L280C16 which [include](https://github.com/ocornut/imgui/blob/d4f722d5b289d4d75b775acfb0a4b41e7df472a7/backends/imgui_impl_opengl3.cpp#L180) all the [symbols](https://github.com/ocornut/imgui/blob/d4f722d5b289d4d75b775acfb0a4b41e7df472a7/backends/imgui_impl_opengl3_loader.h#L147) you are missing. So the problem is that this header is not included in some way.

Ah, I see. That's definitely out of my depth...

> I'm mainly focusing on the sdl part of this project so I don't have any project to test this on. maybe you have some sample project I could try? or maybe the info I gave could help you figure this out ?

Sure! I trimmed away most irrelevant dependencies (zm, zstbi, etc) and some stuff and put together this: <https://github.com/Falkgaard/zgui_mre>

**Comment by Falkgaard** [comment]
> I had the same issue and what [@tonitch](https://github.com/tonitch) wrote is correct.
> 
> I noticed in [imgui_impl_opengl3.cpp](https://github.com/zig-gamedev/zgui/blob/main/libs/imgui/backends/imgui_impl_opengl3.cpp) the following code starting from line 168:
> 
> ...
> 
> So `"imgui_impl_opengl3_loader.h"` is included only if `IMGUI_IMPL_OPENGL_LOADER_CUSTOM` is not defined. To make sure that was the issue I changed it to:
> 
> #elif defined(IMGUI_IMPL_OPENGL_LOADER_CUSTOM)
> 
> And the file was included and the above errors did not happen. Maybe the better solution is to remove the macro from the `build.zig` file of `zgui`.
> 
> I am not sure why this has stopped working as these macros were not changed recently as far as I could see.
> 
> After that I had another issue where the linker did not find the `extern` functions declared in [backend_glfw.zig](https://github.com/zig-gamedev/zgui/blob/main/src/backend_glfw.zig) and [backend_glfw_opengl.zig](https://github.com/zig-gamedev/zgui/blob/main/src/backend_glfw_opengl.zig). What fixed that for me was adding the following line to line 120 in the `build.zig` file of `zgui`:
> 
> imgui.root_module.addCMacro("IMGUI_IMPL_API", "extern \"C\"");
> 
> I am testing it on Windows 11, so I can't confirm if this issue happens on linux as well and the same will work there. I used zgui on linux 2-3 months ago with zig 0.14 and didn't have these issues so I am not sure what happened.

Thank you two very much for the helpful insight!

My main computer broke so I'm also on Windows 11 at the moment, I'll give it a go changing those things that you mentioned. Is making a temporary zgui fork with those changes a good approach (to avoid the build system overwritting any changes)?

**Comment by hazeycode** [comment]
OpenGL backend issue should be fixed by https://github.com/zig-gamedev/zgui/commit/a0fb7ec0ed02ec52e703f5959abe3eb1d70ac68d
