### ISSUE TITLE
#error exactly one of IMGUI_IMPL_WEBGPU_BACKEND_DAWN or IMGUI_IMPL_WEBGPU_BACKEND_WGPU must be defined!

### ISSUE THREAD

**Issue by tadeohepperle** [zig-gamedev/zgui#75]
I can't get `zgui` to compile with zig 0.15.1. The following build error occurs:

```
/home/tadeo/.cache/zig/p/zgui-0.6.0-dev--L6sZL7tbQAPRLYrcQAVx0V49tPHAXNxclZ-v8IP4wLr/libs/imgui/backends/imgui_impl_wgpu.cpp:54:6: error: exactly one of IMGUI_IMPL_WEBGPU_BACKEND_DAWN or IMGUI_IMPL_WEBGPU_BACKEND_WGPU must be defined!
    #error exactly one of IMGUI_IMPL_WEBGPU_BACKEND_DAWN or IMGUI_IMPL_WEBGPU_BACKEND_WGPU must be defined!
```

In the dependencies of my build.zig.zon file I have the following fields:
```
.zgui = .{
    .url = "https://github.com/zig-gamedev/zgui/archive/7fa8081c208885b85e3fdfc043cd9d9cb9559123.tar.gz",
    .hash = "zgui-0.6.0-dev--L6sZL7tbQAPRLYrcQAVx0V49tPHAXNxclZ-v8IP4wLr",
},
.zgpu = .{
    .url = "https://github.com/zig-gamedev/zgpu/archive/96f3ce2229e4836daec714a3f0b8c3c3218a6b2c.tar.gz",
    .hash = "zgpu-0.12.0-dev-nqFT5LqgCACR_1wEhi7rveY3ocKJczfRaXQoisCmpohn",
},
.dawn_x86_64_linux_gnu = .{
    .url = "https://github.com/michal-z/webgpu_dawn-x86_64-linux-gnu/archive/7d70db023bf254546024629cbec5ee6113e12a42.tar.gz",
    .hash = "N-V-__8AAK7XUQNKNRnv1J6i189jtURJKjp3HTftoyD4Y4CB",
    .lazy = true,
},
```
In my build.zig file I have these lines:
```zig
@import("zgpu").addLibraryPathsTo(exe);
const zgpu = b.dependency("zgpu", .{});
exe.root_module.addImport("zgpu", zgpu.module("root"));
exe.linkLibrary(zgpu.artifact("zdawn"));
const zgui = b.dependency("zgui", .{
    .target = target,
    .backend = .glfw_wgpu,
});
exe.root_module.addImport("zgui", zgui.module("root"));
exe.linkLibrary(zgui.artifact("imgui"));
const zglfw = b.dependency("zglfw", .{
    .target = target,
});
exe.root_module.addImport("zglfw", zglfw.module("root"));
exe.linkLibrary(zglfw.artifact("glfw"));
```

If I add a `"-IMGUI_IMPL_WEBGPU_BACKEND_DAWN"` to the cflags in the build.zig file, the error disappears but it complains about not finding some structs like `unknown type name 'WGPUComputeState'`. I think there is either some file not included or there is a version mismatch for the dawn version built by `zgpu`.

**Comment by tadeohepperle** [comment]
> What zig version you have used and did you use the [zgpu from my fork](https://github.com/Logickin-Lambda/zgpu) or from the official branch? I wanna know if this issues is caused from my ends.

I have indeed forked your branch to get 0.15.1 support, see here: https://github.com/tadeohepperle/zgpu

I had to add some code in the build.zig file to let the dawn library link against X11 on Linux correctly. Now zgpu works for me eith that fix, but the dear Imgui wrapper zgui does not. I think these are two separate issues, I am just gonna use zgpu without zgui for now, making my own UI anyway.

**Comment by Logickin-Lambda** [comment]
Found the problem! In the commit for the [imgui update (in imgui_impl_wgpu.h)](https://github.com/zig-gamedev/zgui/commit/96cf8bd517043cbfbc018908c8049184ee6af29e#diff-caf8c6a39c62571bd5bd77c8e3493a4a5c871e1bc36ac277511391599ff23e62), there was possibly a temporary fix to this problem by adding the Macro `IMGUI_IMPL_WEBGPU_BACKEND_WGPU` in the imgui side of the library, but since it was accidentally removed after the updating the imgui library, thus the error.

However, I am more concerned about that there are many other code in imgui of the zgui with `// FIX(zig-gamedev)` got removed since the update, and there are probably issues reported recently related to this reason, but since there is a pr [replacing the original imgui library with cimgui](https://github.com/zig-gamedev/zgui/pull/65), perhaps we could only fix the problems with the immediate effect like this one just to get everyone's projects work for now.

**Comment by Logickin-Lambda** [comment]
The problem is that the wgpu backend was backed by a dead mach engine project which is no longer in maintenance. 

Unfortunately, attempted to do a fix, but due to the lack of knowledge and constantly changing dawn backend, I couldn't manage to  fix it. I knew someone had managed to get it work, but I haven't heard any news about their ends either.

I haven't followed any news about zgpu or zgui for a month, so I hope I am outdated about this issue.

**Comment by LordSk** [comment]
I just stumbled on this issue myself while upgrading my project to 0.15.2.
The quick fix I found is to simply remove the error message:

`libs/imgui/backends/imgui_impl_wgpu.cpp`
```cpp
// When targeting native platforms (i.e. NOT emscripten), one of IMGUI_IMPL_WEBGPU_BACKEND_DAWN
// or IMGUI_IMPL_WEBGPU_BACKEND_WGPU must be provided. See imgui_impl_wgpu.h for more details.
#ifndef __EMSCRIPTEN__
    // #if defined(IMGUI_IMPL_WEBGPU_BACKEND_DAWN) == defined(IMGUI_IMPL_WEBGPU_BACKEND_WGPU)
    // #error exactly one of IMGUI_IMPL_WEBGPU_BACKEND_DAWN or IMGUI_IMPL_WEBGPU_BACKEND_WGPU must be defined!
    // #endif
#else
```
